apiVersion: v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        name: monitoring-agent
    spec:
      containers:
        - name: monitoring-agent
          image: monitoring-agent
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
