apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replica
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  selector:
    app: myapp-pod
  template:
    metadata:
      name: mynginx-pod
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
