apiVersion: v1
kind: Config

current-context: dev-user@google

clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: ca.crt
      server: https://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin

  - name: dev-user@google

  - name: prod-user@production
    context:
      cluster: production
      user: admin
      namespace: finance

users:
  - name: my-kube-admin
    user:
      client-certificate: admin.crt
      client-key: admin.key
